print('Welcome to the TVM Calculator - this is just a project for me to figure out a slightly more complex program.')
print('This TVM Calculator was built by Michael.')
pv = input('Principal Value?')
print('PV =', pv)
n2 = input('Time?')
print('Time =', n2)
APR = input('APR?')
print('APR =', APR)
pmt = input ('yearly payment totals?')
print('Payment =', pmt)
